### PR TITLE
Ukrainian and Russian languages have been added

### PR DESCRIPTION
**Pull request by popovsergiy**
In most Slavonic languages sentence construction is common. For this purpose I had created folder Slavonic in Grammar and grouped abstract classes here. If this is bad place you can offer more right.

### CODE REVIEW

**Comment by kwn** [comment]
Hi @popovsergiy

Thank you for your contribution. I'll review it tomorrow. Btw, could you meanwhile have a quick look at Travis result, please? It seems some tests are failing there.

Thanks.

**Comment by popovsergiy** [comment]
I am sorry. Tests have been fixed.

**Comment by kwn** [comment]
@popovsergiy 

Thanks! Could you also have a quick look at travis output (phpcs section), please? 

https://travis-ci.org/kwn/number-to-words/jobs/127427298

It seems there are a lot of coding style issues. I follow PSR-2, which is broadly accepted standard in php community. I'll review your code and I'll put some more comments in the evening.

**Comment by popovsergiy** [comment]
I change all code style to PSR-2 but `phpcs` anyway has "errors" like this
```sh
FILE: ...d/kwn/number-to-words/src/Language/Russian/Dictionary/Number.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 12 | WARNING | Line exceeds 120 characters; contains 131 characters
 13 | WARNING | Line exceeds 120 characters; contains 131 characters
----------------------------------------------------------------------
```
I suppose this is not error. `phpcs` sees cyrillic not as multibyte coding but as sets of signs.
For example: "один" is 4 signs but for `phpcs` it is whole 8 signs.
Here I don't help.

**Comment by kwn** [comment]
@popovsergiy 

Dear Sergyi. I'm really happy to merge your contribution! Thank you very much for your work. I'll add you to contributors list in README file. I hope it's not a problem for you.

In terms of failing `phpcs` it's my fault and it seems I need to run `phpcs` with `--encoding=utf-8` switch. I'll update it and I'll create a new tag for the package. 

Once again, thank you for your hard work!

**Comment by popovsergiy** [comment]
@kwn 

You're welcome. 
When you will implement "angle" and "temperature" modes give me know I will try contribute improvement.

**Comment by kwn** [comment]
@popovsergiy 

Sure thing. It should be pretty straightforward as it just requires to generate "number in words + morphed word describing angle or temperature".

Once again, thank you!

**Pull request merged**
