### PR TITLE
Fixes Persian number converter

### LINKED ISSUE #98: Persian Support
Hi folks.

I Like the idea of supporting multiple languages in single library. So just tried ti implement Persian **based on English** classes.

It turned out its not possible to do such using current `GenericNumberTransformerBuilder` and it needs some modifications ( Adding another property like `$tripletSeparator`  and modifying some parts might solve this but seems overkill to me).

I spent last couple of hours and [made](https://github.com/mojtabaahn/php-persian-number-to-words) a number to words translator from scratch for Persian language. It has same test suite as english test and it is passing.

So was wondering if you have any interests in me creating a `NumberTransformer` wrapper for this language-specific implementation and make a pull request.

### PR DESCRIPTION
**Pull request by mojtabaahn**
Fixes #98

### CODE REVIEW

**Comment by kwn** [comment]
Hi @mojtabaahn 

Thank you for the contribution. Could you please take a look at Code Sniffer output and fix the issues? You can run Code Sniffer locally by typing `make phpcs`. Thank you!

**Comment by mojtabaahn** [comment]
Hi @kwn. sorry I didn't notice it earlier, I think it should be okay now 🤘

**Review by kwn — APPROVED** [review]
Thank you for your support!

**Comment by kwn** [comment]
Released in `2.1.1`

**Pull request merged**
