### PR TITLE
Fix missing "one" for "one hundred" in Latvian

### PR DESCRIPTION
**Pull request by CreepPork**

### CODE REVIEW

**Comment by kwn** [comment]
Hi @CreepPork 

Thank you for fixing the issue. I pulled your changes and apparently there are still some broken tests. Could you please double check if they are all green?

**Comment by CreepPork** [comment]
@kwn I fixed all the test errors regarding the Latvian translations.

**Comment by CreepPork** [comment]
@kwn Could you look at this PR, if you have the chance?

**Review by kwn — APPROVED** [review]

**Comment by kwn** [comment]
Hi @CreepPork 

Thank you. Just merged and released your fix in `2.3.1` version.

**Pull request merged**
