### PR TITLE
Update UA locale.

### PR DESCRIPTION
**Pull request by TheMY3**
For now in  `$currencyNames` russian words, not ukrainian, fix it.

### CODE REVIEW

**Comment by TheMY3** [comment]
@kwn waiting for you reply :)

**Comment by TheMY3** [comment]
@kwn ping

**Comment by kwn** [comment]
Hi @TheMY3

Thank you for your contribution. Could you please review and update tests?

https://github.com/kwn/number-to-words/blob/master/tests/CurrencyTransformer/UkrainianCurrencyTransformerTest.php

I think they will fail once you run them. I also reconfigured CI so it will run tests automatically for a forked pull requests.

**Comment by TheMY3** [comment]
@kwn fix tests, that was my mistake, but CU build broken, please check it

**Comment by kwn** [comment]
Ok, I just updated CI configuration and now it passed successfully.

**Review by kwn — APPROVED** [review]

**Comment by kwn** [comment]
Thank you for fixing it!!

**Comment by TheMY3** [comment]
> Thank you for fixing it!!

And you, waiting for release now :slightly_smiling_face:

**Comment by kwn** [comment]
Released in 2.7.1. Thanks!!

**Pull request merged**
