### PR TITLE
Fixed russian language

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by kwn** [comment]
Thank you once again for all of your contributions!

**Comment by andrey-helldar** [comment]
@kwn, your kung-fu is stronger than [mine](https://packagist.org/packages/andrey-helldar/digittext).

So, I will use your package 😊

**Comment by kwn** [comment]
@andrey-helldar 
Heh, thanks ;) BTW we can still move some test cases from your repo. I'll take a look how did you handle the number to words conversion, since I still don't know how to handle it properly. Lots of my code comes from pear/Number_To_Words package which is really crappy.

**Comment by andrey-helldar** [comment]
We will understand :)

In my package, the only [problems found|https://github.com/andrey-helldar/DigitText/issues?q=is%3Aissue+is%3Aclosed] were the conversion of the numbers 11000 and 7700

**Pull request merged**
