### PR TITLE
Azerbaijani Language

### PR DESCRIPTION
**Pull request by kongulov**

### CODE REVIEW

**Comment by kongulov** [comment]
@kwn Hello.
"Travis CI - Pull Request" returns "Build Errored". But I'm not sure if it's because of the code. One build was successful and the other was not.

**Comment by kongulov** [comment]
@kwn @CreepPork @mojtabaahn @shahonseven @AvdylKrasniqi 
Hello.
"Travis CI - Pull Request" returns "Build Errored". But I'm not sure if it's because of the code. One build was successful and the other was not.

**Comment by kwn** [comment]
Hi @kongulov 

Thank you for your contribution. I think it's an internal Travis issue. Let me take a deeper look at that.

**Comment by kongulov** [comment]
@kwn Any progress?

**Review by kwn — APPROVED** [review]

**Comment by kwn** [comment]
Thanks @kongulov

Just released version 2.3.0 with your improvement. Thank you!!

**Pull request merged**
