### PR TITLE
Kurdish language

### PR DESCRIPTION
**Pull request by jihad28**
I have added support for Kurdish language and wrote the tests.
Hope you include it in your library and thank you for this work.

### CODE REVIEW

**Comment by jihad28** [comment]
@kwn can you merge it?

**Comment by kwn** [comment]
Actually I can reopen it myself. Let me review it and I'll get back to you.

**Comment by jihad28** [comment]
Hi, I'm sorry I deleted the forked repo and didn't know that this will be closed automatically.
Yes, please review it.

**Review by kwn — APPROVED** [review]
Looks great. Thank you!!

**Pull request merged**
