### PR TITLE
Improve Latvian dictionary

### PR DESCRIPTION
**Pull request by CreepPork**

### CODE REVIEW

**Comment by kwn** [comment]
Hi @CreepPork 

Thank you for your pull request. Could you please take a look and fix unit tests?

**Comment by CreepPork** [comment]
Sure thing, I'll update it soon.

**Comment by CreepPork** [comment]
I've fixed all the tests only regarding the Latvian translation.

**Comment by kwn** [comment]
Thank you. I'll merge it and will fix the phpcs issues on my own. Thank you 👍

**Comment by kwn** [comment]
Released in `2.2.1`

**Pull request merged**
