### PR TITLE
Serbian language added

### PR DESCRIPTION
**Pull request by amici**
- with plurals, genders and appropriate tests

### CODE REVIEW

**Comment by kwn** [comment]
Hey @amici 

This looks great and very promising. Is there any reason why did you close the PR?

**Comment by amici** [comment]
> Hey @amici
> 
> This looks great and very promising. Is there any reason why did you close the PR?

Yes, I figured out it had a few issues. I didn't realize how complicated Serbian can be. :)  I'm fixed those and also added the currency translations. plus some tests. I'll make a new one.

BTW, tnx for asking! Very nice of you.

**Comment by kwn** [comment]
Perfect, thank you :)

**Review by Sekara — APPROVED** [review]
As a native Serbian speaker I can confirm that this is 100% grammatically correct.

**Review by dcbi-cos — APPROVED** [review]

**Review by kwn — APPROVED** [review]

**Comment by kwn** [comment]
Amazing, thank you for the contribution!

**Pull request merged**
