### PR TITLE
Uzbek language added

### PR DESCRIPTION
**Pull request by Olimovv**

### CODE REVIEW

**Comment by Olimovv** [comment]
@kwn please check is my code?

**Comment by Olimovv** [comment]
🙄🙄

**Comment by kwn** [comment]
Hey @Olimovv 

I'm hoping to review the code over the weekend. Meanwhile - could you please order currencies and languages in the arrays alphabetically? Thanks.

**Comment by Olimovv** [comment]
??

**Review by kwn — APPROVED** [review]

**Comment by kwn** [comment]
Thank you for your contribution! I'll test and release it soon.

**Comment by kwn** [comment]
Hi @Olimovv 
I had to revert your PR because tests are failing. I'm going to fix the missing CI/CD integration so it runs against your branch.

**Comment by kwn** [comment]
Hey @Olimovv 

I replaced the old CI tool (TravisCI) that stopped working with CircleCI. It should run the tests without any issues now.

Could you please run the tests again, fix the broken ones and re-open pull request? It would be a bit of a shame if we didn't include your language, since you have already implemented it.

Thank you in advance and sorry for a late reply.

**Comment by Olimovv** [comment]
yes, I understand.

**Comment by kwn** [comment]
@Olimovv 
Great. Please let me know once you fix tests and reopen the PR. Thank you in advance.

**Comment by kwn** [comment]
Hey @Olimovv 

Did you have a chance fix tests so you can re-open the pull request?

**Pull request merged**
