### PR TITLE
French Language

### PR DESCRIPTION
**Pull request by Zehir**
Adding the French language

### CODE REVIEW

**Comment by Zehir** [comment]
Some conversions are note good but I working on it

**Comment by Zehir** [comment]
I ended up adding the french language.
Everything works fine.
In the travis build the error that appears is because of composer ...

**Comment by Zehir** [comment]
Finally, it works!

**Comment by Zehir** [comment]
My fix work but break other case... 
I working on as other fix

**Comment by kwn** [comment]
Hi @Zehir 

I'm really sorry but I didn't notice your PR. I'll review it in a minute. Once again, sorry you had to wait so long.

**Comment by kwn** [comment]
Hello again @Zehir 

Your PR looks amazing! I believe all translations are correct, because I don't know French :) I've just quickly checked a few of them using a google translator and it just works like a charm. I happy to merge it.

Thank you for your contribution!

**Comment by Zehir** [comment]
Hello,

Thank you for your message, I spent a lot of time to solve some subtleties of the French language. He may have a few problems that would have me efcaped. But I added a lot of test cases that worked. So I hope all is good. Should I make a PR;)

**Comment by kwn** [comment]
@Zehir 

Yeah, I've seen the French grammar in terms of numbers is really crazy ;) Thank you for your time again.

Everything is fine and I've just bumped a version to 0.0.2 :+1:

**Pull request merged**
